### ISSUE TITLE
generate_index.py changes

### ISSUE THREAD

**Issue by donjan** [FrescolinoGroup/Frescolino#1]
1. always copy (symlink?) from `media/` to website/frescolino/static to avoid double maintenance

2. move to helpers/ because

- doc generation for modules also happens from outside website repo

- need to pull additional resources (media data, doc_src) from outside

- it's a helper script and then we have generation in one place

**Comment by mskoenz** [comment]
submodule doc building works only with base package bc:
1) we want to build to website to avoid missing a version
2) we reuse the resources (easy maintenance)

adopting 1: generate_index.py should copy from media to static

**Comment by mskoenz** [comment]
2: move when necessary

**Comment by mskoenz** [comment]
1: is now implemented
