### ISSUE TITLE
review pyio_helper

### ISSUE THREAD

**Issue by greschd** [FrescolinoGroup/Frescolino#4]

**Comment by greschd** [comment]
This can wait -- I should first find a way to allow more than one encoding to be used concurrently.

**Comment by greschd** [comment]
Ready for review.

**Comment by mskoenz** [comment]
starting review

**Comment by mskoenz** [comment]
Following fails:
cd pyio_helper/..
mkvirtualenv test_pyio #is a python3.5.2
(test_pyio) pip install pyio_helper
(test_pyio) cd pyio_helper/doc
(test_pyio) make

with the following error:

Exception occurred:
  File "conf.py", line 22, in <module>
ImportError: No module named 'fsc'

even:
(test_pyio) pip install fsc

does not fix it...
@greschd: do you get the same mistake or is it just me?

**Comment by mskoenz** [comment]
Trying to import now something from fsc results in:

Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
**>>> from fsc import pylocker**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mskoenz/.virtualenvs/test_fsc/lib/python3.5/site-packages/fsc/__init__.py", line 19, in <module>
    importlib.import_module(modname, package='fsc') 
  File "/home/mskoenz/.virtualenvs/test_fsc/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ImportError: No module named 'fsc.io-helper'**
>>>

**Comment by greschd** [comment]
It's just you ??

**Comment by greschd** [comment]
Does

    cd pyio_helper
    pip install .

work?

**Comment by greschd** [comment]
This reminds me of the problem I got which made me drop Python2 support. Maybe something about the dash vs. underscore in package names?

**Comment by mskoenz** [comment]
(test_fsc) mskoenz@Abakus2:~/Programmieren/eth/frescolino_2.0/modules/pyio_helper$ **pip install .**
Processing /home/mskoenz/Programmieren/eth/frescolino_2.0/modules/pyio_helper
Requirement already satisfied (use --upgrade to upgrade): msgpack-python in /home/mskoenz/.virtualenvs/test_fsc/lib/python3.5/site-packages (from fsc.io-helper==0.0.0)
Requirement already satisfied (use --upgrade to upgrade): fsc.export in /home/mskoenz/.virtualenvs/test_fsc/lib/python3.5/site-packages (from fsc.io-helper==0.0.0)
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python3.5/dist-packages (from fsc.io-helper==0.0.0)
Installing collected packages: fsc.io-helper
  Running setup.py install for fsc.io-helper ... done
Successfully installed fsc.io-helper-0.0.0
(test_fsc) mskoenz@Abakus2:~/Programmieren/eth/frescolino_2.0/modules/pyio_helper$ python
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> **from fsc import io_helper**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mskoenz/Programmieren/eth/frescolino_2.0/modules/pyio_helper/fsc/io_helper/__init__.py", line 15, in <module>
    from ._version import __version__
  File "/home/mskoenz/Programmieren/eth/frescolino_2.0/modules/pyio_helper/fsc/io_helper/_version.py", line 10, in <module>
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'version.txt'), 'r') as f:
FileNotFoundError: [Errno 2] **No such file or directory: '/home/mskoenz/Programmieren/eth/frescolino_2.0/modules/pyio_helper/fsc/io_helper/version.txt'**
>>>

**Comment by mskoenz** [comment]
@greschd: what is your sphinx version?

**Comment by greschd** [comment]
1.4.4

**Comment by greschd** [comment]
I propose changing the name to iohelper https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by mskoenz** [comment]
the link issues disappear if you: pip install -e .

but the sphinx makefile still tells me: no fsc found...

**Comment by mskoenz** [comment]
+1 for name change, I thought: underscore?!

**Comment by greschd** [comment]
Underscore gets changed to a hyphen somehow in some instances -- i guess that's why it's discouraged in  PEP8.

**Comment by greschd** [comment]
I'll do the name change, if it works out I think we should also rename the repo.

**Comment by mskoenz** [comment]
works for me, let me rename the repo after review

**Comment by mskoenz** [comment]
pip3 freeze: ....sphinx 1.4.8.
workon test_fsc
(test_fsc): .../doc: make

Running Sphinx v1.4.8

Exception occurred:
  File "conf.py", line 22, in <module>
**ImportError: No module named 'fsc'**
The full traceback has been saved in /tmp/sphinx-err-2zn4l7vw.log, if you want to report the issue to the developers.

**Comment by mskoenz** [comment]
I doubt that it is a sphinx issue...

**Comment by greschd** [comment]
Are you sure you're running Sphinx on python3?

**Comment by mskoenz** [comment]
how do I check? I did install it with pip3....

**Comment by greschd** [comment]
Maybe we can re-introduce Python2 support though when changing the name.

**Comment by greschd** [comment]
Write Python3 - syntax in conf.py XD

**Comment by mskoenz** [comment]
I have a superposition O_o
First line in conf.py:

print 1/2

Works but print 0.5

**Comment by mskoenz** [comment]
I try it without --system-site-packages

**Comment by greschd** [comment]
I think we should make it s.t. it works in both cases. The name is changed now, you can try again.

**Comment by greschd** [comment]
That's not a superposition, that's Python 2 with ``__future__`` import.

**Comment by mskoenz** [comment]
now it works, the external sphinx must have been python2, sry

**Comment by mskoenz** [comment]
will continue review tomorrow

**Comment by greschd** [comment]
Ok. Should I move the repo or will you do it? Where do I need to change 
the name for the submodule?

**Comment by greschd** [comment]
I did the renaming -- is the old module deleted on your system when pulling the main repo? Can you try if the old module is properly deleted on your system when you pull the main repo?

**Comment by greschd** [comment]
@mskoenz  - "tomorrow"

**Comment by mskoenz** [comment]
tomorrow is upon us :D

**Comment by greschd** [comment]
yay :)

**Comment by mskoenz** [comment]
Disclaimer: Whenever I review, I'm not putting much effort in tone. There are my subjective suggestions and I apologize for imperative/direct formulation...

Tutorial
---------
* IO_HELPER: why in caps? isn't there a pep against it?
* Introduction not so logical (maybe too concise?). I would suggest starting with the code (line by line) and explain what happens after every line. The "summary" in the beginning had too much information imo.(object_hook and default should be closer to load and dump, since it was not clear to me that you refer to extern doc "parameters")
* I would suggest you throw already on filesave when the ending is not understood. It's strange to be able to save but then not load and it makes the code more readable.
* If the serializer is specified, shouldn't it be possible to pass any filename (with arbitrary ending) nstead of 'filename_without_ending'?

* maybe a very small example (that handles just int) on how I would write my own encoder?

Documentation
-------------------

* class fsc.iohelper.SerializerDispatch(encoding):
    * again, move object_hook and default closer to the links and make sure it's clear that there are parameters of these "links"
    * remove caps?
* load(file_path, serializer='auto')
    * path: I assume abs and rel work?
    *  tries to guess -> colloquial -> infers/deduces
* save(obj, file_path, serializer='auto')
    * atomic everywhere? :P -> specify limitations or at least link to used package

**Comment by mskoenz** [comment]
PS: an error is thrown -> error is raised (too much c++ lately :P)

**Comment by greschd** [comment]
implemented changes, pls review again

**Comment by mskoenz** [comment]
Tutorial
----------
* note: error is thrown -> raised? + mention save no error for data loss prevention maybe?

* custom: JSON / msgpack - compatible type: (mention that only there two need encoding since pickle handles all) bonus: what if I write an encoding that stores lambdas for pickle?

* encoding.default#source link is dead

* Possible file endings are .json for JSON files, .msgpack for msgpack, and .p or .pickle for pickle: mention case insensitive
